# @format

version: "3"
services:
  # app:
  #   container_name: slack-socket
  #   build: .
  #   volumes:
  #     - ./:/var/app
  #   env_file:
  #     - .env
  cdk:
    container_name: slack-concierge-cdk
    build:
      context: ./
      dockerfile: ./docker/cdk/Dockerfile
    volumes:
      - ./cdk:/var/cdk
      - ~/.aws:/root/.aws
    tty: true
