# @format

version: "3.0"

services:
  api:
    container_name: "slack-concierge-api"
    volumes:
      - ./slack:/workspace/slack:cached
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    working_dir: /workspace/slack
    command: pipenv run uvicorn fastapi_main:app --reload --port=8080 --host=0.0.0.0
    # command: bash
    ports:
      - 10314:8080
    tty: true
