[tool.ruff]
target-version = "py311" # Pythonのバージョンを指定

# NOTE: 不要なルールがあれば追加してください
ignore = [
  "D",      # ドキュメント関連の警告を無視
  "ANN101", # 型ヒントがない場合の警告を無視
  "TD",     # ドキュメントの型ヒントがない場合の警告を無視
  "FIX",    # FIXMEコメントがある場合の警告を無視
  "T201",   # print文がある場合の警告を無視
]
select = ["ALL"] # ignore以外のすべてのルールを適用する

line-length = 120

[tool.ruff.pydocstyle]
convention = "google" # docstringの形式を指定
