[tool.ruff]
target-version = "py311" # Pythonのバージョンを指定
fix = true # 自動修正を有効にする
indent-width = 4 # インデントの幅を指定
tab-size = 4 # タブの幅を指定
src = ["slack"]

# NOTE: 不要なルールがあれば追加してください
ignore = [
  "D",      # ドキュメント関連の警告を無視
  "ANN101", # 型ヒントがない場合の警告を無視
  "TD",     # ドキュメントの型ヒントがない場合の警告を無視
  "FIX",    # FIXMEコメントがある場合の警告を無視
  "T201",   # print文がある場合の警告を無視
  "TRY",    # try-except文がある場合の警告を無視
]
select = ["ALL"] # ignore以外のすべてのルールを適用する

line-length = 120

[tool.ruff.pydocstyle]
convention = "google" # docstringの形式を指定

[tool.ruff.lint.mccabe] # 複雑度の設定
max-complexity = 5 # 複雑度が5を超えると`C901`の警告を出す
